name: Render Control

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
    secrets:
      RENDER_SERVICE_ID:
        required: true
      RENDER_API_KEY:
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render API
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          API_KEY: ${{ secrets.RENDER_API_KEY }}
          ACTION: ${{ inputs.action }}
        run: |
          CMD="curl -s -o response.txt -w \"%{http_code}\" -X POST \
          \"https://api.render.com/v1/services/${SERVICE_ID}/${ACTION}\" \
          -H \"Accept: application/json\" \
          -H \"Authorization: Bearer ${API_KEY}\""

          echo "Comando curl que seria executado:"
          echo "$CMD"